##################################################################
# Author: Kazoo	 & Tabinol                                       #
# Copyrigth 2013      	                                         #
# Website: http://dev.bukkit.org/profiles/darkkazoo/             #
# Contact: dev.kazoo@gmail.com                	                 #
##################################################################
general:                             #----General Config----
  debug: false                       #Set to true to show DebugLog 
  lang: english
  Storage: flat                      #Only flat is supported for now
  worlds: [world, world_nether, world_the_end] # World where Factoid is enable
  # The next value is if you want the Factoid exposion protection.
  # Set it to «False» if you prefere to disable explosions from Essentials
  # or avoiding plugin conflicts. any other plugin. Flags (???_DAMAGE) will 
  # be ignored.
  OverrideExplosions: true
  UseEconomy: false
  InfoItem: 352                      # Item that give Land information
  SelectItem: 367                    # Item that give Land selection
land:
  PriorityOld: false
  CanMakeCollision: false
  MaxLand: 1
  MinLandSize: 1
  MaxLandSize: 1
  MinLandHigh: 0
  MaxLandHigh: 255
  area:
    MinAreaSize: 1
    MaxAreaSize: 1
    MaxAreaPerLand: 1
  OwnerCanSet:                     # What the owner can set on his land?
    Permissions: [BUILD, OPEN, USE]
    Flags: [MESSAGE_JOIN, MESSAGE_QUIT]
  BeaconLigth: false               #Set beacon ligth effect of an selection
economy:
  PricebyCube: 100
  MinPriceLocation: 1
  MaxPriceLocation: 1
  MinPriceSell: 1
  MaxPriceSell: 1