##################################################################
# Author: Kazoo	 & Tabinol                                       #
# Copyrigth 2013					                                       #
# Website: http://dev.bukkit.org/profiles/darkkazoo/		         #
# Contact: dev.kazoo@gmail.com                	                 #
##################################################################
general:                             #----General Config----
  debug: false                       #Set to true to show DebugLog 
  lang: english
  Storage: flat                      # Only flat is supported for now
  worlds: [world]                    # World where Factoid is enable
  UseEconomy: false
  InfoItem: 352                      # Item that give Land information
land:
  PriorityOld: false
  CanMakeCollision: false
  MaxLand: 1
  MinLandSize: 1
  MaxLandSize: 1
  MinLandHigh: 0
  MaxLandHigh: 255
  area: 
    MinAreaSize: 1
    MaxAreaSize: 1
    MaxAreaPerLand: 1
  DefaultConfig:
    ContainerPermissions:          # Default Config when land is created
      - 'Everybody::BUILD_PLACE:False:True'
      - 'Everybody::BUILD_DESTROY:False:True'
      - 'Owner::BUILD_PLACE:True:True'
      - 'Owner::BUILD_DESTROY:True:True'
      - 'Resident::BUILD_PLACE:True:False'
      - 'Resident::BUILD_DESTROY:True:False'
    ContainerFlags:
      - 'CREEPER_DAMAGE:False:True'
  OwnerCanSet:                     # What the owner can set on his land?
    Permissions: [BUILD_PLACE, BUILD_DESTROY]
    Flags: [MESSAGE_JOIN, MESSAGE_QUIT]

world:                             # Config for Global and specific worlds
  _Global_:
    ContainerPermissions:
      - 'Group:Newbies:BUILD_PLACE:False:True'
      - 'Group:Newbies:BUILD_DESTROY:False:True'
      - 'Everybody::BUILD_PLACE:True:False'
      - 'Everybody::BUILD_DESTROY:True:False'
      - 'Everybody::DROP:True:False'
    ContainerFlags:
      - 'FIRESPREAD:False:True'
      - 'FIRE:True:True'
      - 'CREEPER_DAMAGE:True:True'
#  world1:
#    ContainerPermissions:
#      - 'Everybody::BUILD_PLACE:True:False'
#      - 'Everybody::BUILD_DESTROY:True:False'
#      - 'Everybody::DROP:True:False'
#    ContainerFlags:
#      - 'FIRESPREAD:False:True'
#      - 'FIRE:True:True'
#      - 'CREEPER_DAMAGE:False:True'
    
economy:
  PricebyCube: 100
  MinPriceLocation: 1
  MaxPriceLocation: 1
  MinPriceSell: 1
  MaxPriceSell: 1
   