name: Factoid
main: me.tabinol.factoid.Factoid
version: 0.1
description: Factoid
author: [Kaz00,Tabinol]
depend: [Vault]
commands:
   factoid:
      description: Factoid Command
      alias: claim
      usage: /factoid help
      permission: factoid.use
      permission-message: you don't have permission for that!
permissions:
    factoid.*:
        description: ModulMonde Command Permission
        default: op
        children:
            factoid.adminmod: true
            factoid.use: true
    factoid.adminmod:
        description: Can use Admin Mod
        default: op
    factoid.use:
        description: Can use factoid command
        default: op
