_Global_:                           # _Global_ for all worlds
  ContainerPermissions:
    Group:
      Newbies:
        BUILD:
          Value: false
          Heritable: true
    Everybody:
      LAND_CREATE:
        Value: true
        Heritable: false
      BUILD:
        Value: true
        Heritable: false
  ContainerFlags:
    CREEPER_DAMAGE:
      Value: true
      Heritable: false
    ECO_BLOCK_PRICE:
      Value: 0.01
      Heritable: true
#world1:
#  ContainerPermissions:
#    Group:
#      Newbies:
#        BUILD_PLACE:
#          Value: false
#          Heritable: true
#        BUILD_DESTROY:
#          Value: false
#          Heritable: true
#    Everybody:
#      BUILD_PLACE:
#        Value: true
#        Heritable: false
#      BUILD_DESTROY:
#        Value: true
#        Heritable: false
#  ContainerFlags:
#    CREEPER_DAMAGE:
#      Value: true
#      Heritable: false
