##################################################################
# Author: Kazoo						            #
# Copyrigth 2013					            #
# Website: http://dev.bukkit.org/profiles/darkkazoo/		    #
# Contact: dev.kazoo@gmail.com                	            #
##################################################################
general:                             #----General Config----
  debug: false                       #Set to true to show DebugLog 
mysql:
  username: "root"
  password: ""
  host: "localhost"
  database: "kstat"
   