name: ModulMonde
main: Kazoo.ModulMonde.Main
version: 1.2
description: System ModulMonde
author: Kaz00
depend: [GroupManager,Vault]
commands:
   modul:
      description: ModulMonde Command
      usage: /modul help
      permission: modul.use
      permission-message: you don't have permission for that!
   tpevent:
      description: ModulMonde Event Command
      usage: /modul help
      permission: modul.use
      permission-message: you don't have permission for that!
   tpsetevent:
      description: ModulMonde Set Event Command
      usage: /modul help
      permission: modul.adminevent
      permission-message: you don't have permission for that!
permissions:
    modul.*:
        description: ModulMonde Command Permission
        default: true
        children:
            modul.use: true
            modul.event: true
            modul.adminevent: false
            modul.accept: false
            modul.see: false
            modul.reload: false
            modul.news: true
            modul.search: false
    modul.use:
        description: Permet d'utiliser la commande
        default: true
    modul.event:
        description: Permet de voir les evenement
        default: true
    modul.adminevent:
        description: Permet d'administrer les evenement
        default: false
    modul.accept:
        description: Accepte un joueur au rang d'Aspirant
        default: false
    modul.see:
        description: Obtenir les informations sur un joueur
        default: false
    modul.reload:
        description: Permet de recharger les joueurs en ligne
        default: false
    modul.news:
        description: Permet de voir les nouvelles
        default: true
    modul.search:
        description: Obtenir la liste des nouveaux
        default: false